### ISSUE TITLE
Page fails to load with 404 for linked elements

### ISSUE THREAD

**Issue by quazgar** [quazgar/openproject_install#1]
After running the script, `index.html` is served correctly, but all linked elements (css, js, images) return a 404 error.

This is the logging output:
> F, [2018-03-03T15:19:53.835588 #26588] FATAL -- :
F, [2018-03-03T15:19:53.835721 #26588] FATAL -- : ActionController::RoutingError (No route matches [GET] "/assets/enterprise_edition-c7c654e772b2c7d9d420fc7c47265b8f40340edf22a5bee885c5f150f9bc5797.png"):
F, [2018-03-03T15:19:53.835772 #26588] FATAL -- :
F, [2018-03-03T15:19:53.835835 #26588] FATAL -- : vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.6/lib/action_dispatch/middleware/debug_exceptions.rb:53:in `call'
vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.6/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/rack/logger.rb:36:in `call_app'
vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/rack/logger.rb:24:in `block in call'
vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.6/lib/active_support/tagged_logging.rb:69:in `block in tagged'
vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.6/lib/active_support/tagged_logging.rb:26:in `tagged'
vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.6/lib/active_support/tagged_logging.rb:69:in `tagged'
vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/rack/logger.rb:24:in `call'
vendor/bundle/ruby/2.4.0/gems/request_store-1.3.2/lib/request_store/middleware.rb:9:in `call'
vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.6/lib/action_dispatch/middleware/request_id.rb:24:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/runtime.rb:22:in `call'
vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.6/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.6/lib/action_dispatch/middleware/executor.rb:12:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/sendfile.rb:111:in `call'
vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/engine.rb:522:in `call'
vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/railtie.rb:193:in `public_send'
vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/railtie.rb:193:in `method_missing'
vendor/bundle/ruby/2.4.0/gems/rack-protection-2.0.0/lib/rack/protection/frame_options.rb:31:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-protection-2.0.0/lib/rack/protection/json_csrf.rb:26:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rackloaded/urlmap.rb:68:in `block in call'
vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/urlmap.rb:53:in `each'
vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/urlmap.rb:53:in `call'
vendor/bundle/ruby/2.4.0/gems/unicorn-5.3.1/lib/unicorn/http_server.rb:606:in `process_client'
vendor/bundle/ruby/2.4.0/gems/unicorn-worker-killer-0.4.4/lib/unicorn/worker_killer.rb:92:in `process_client'
vendor/bundle/ruby/2.4.0/gems/unicorn-worker-killer-0.4.4/lib/unicorn/worker_killer.rb:52:in `process_client'
vendor/bundle/ruby/2.4.0/gems/unicorn-5.3.1/lib/unicorn/http_server.rb:702:in `worker_loop'
vendor/bundle/ruby/2.4.0/gems/unicorn-5.3.1/lib/unicorn/http_server.rb:549:in `spawn_missing_workers'
vendor/bundle/ruby/2.4.0/gems/unicorn-5.3.1/lib/unicorn/http_server.rb:142:in `start'
vendor/bundle/ruby/2.4.0/gems/unicorn-5.3.1/bin/unicorn:126:in `<top (required)>'
vendor/bundle/ruby/2.4.0/bin/unicorn:23:in `load'
vendor/bundle/ruby/2.4.0/bin/unicorn:23:in `<top (required)>'
/home/quazgar4/.gem/ruby/2.4.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `load'
/home/quazgar4/.gem/ruby/2.4.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `kernel_load'
/home/quazgar4/.gem/ruby/2.4.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:28:in `run'
/home/quazgar4/.gem/ruby/2.4.0/gems/bundler-1.16.1/lib/bundler/cli.rb:424:in `exec'
/home/quazgar4/.gem/ruby/2.4.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'loaded
/home/quazgar4/.gem/ruby/2.4.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/quazgar4/.gem/ruby/2.4.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/home/quazgar4/.gem/ruby/2.4.0/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'
/home/quazgar4/.gem/ruby/2.4.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/home/quazgar4/.gem/ruby/2.4.0/gems/bundler-1.16.1/lib/bundler/cli.rb:18:in `start'
/home/quazgar4/.gem/ruby/2.4.0/gems/bundler-1.16.1/exe/bundle:30:in `block in <top (required)>'
/home/quazgar4/.gem/ruby/2.4.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
/home/quazgar4/.gem/ruby/2.4.0/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
/home/quazgar4/.gem/ruby/2.4.0/bin/bundle:23:in `load'
/home/quazgar4/.gem/ruby/2.4.0/bin/bundle:23:in `<main>'

![Screenshot of the Firefox debugging window](https://user-images.githubusercontent.com/302587/36935339-0ecebd60-1ef7-11e8-9f36-ba741e760b2f.png)

**Comment by quazgar** [comment]
Note to self: in `config/environments/production.rb`, set `config.public_file_server.enabled = true` to serve the static elements.
